services:
  - type: web
    name: omni-backend
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
